---
# Set up the pieces required to run clojure.
# Note that this really means installing leiningen
- name: Get leiningen
  sudo: True
  get_url: url=https://raw.github.com/technomancy/leiningen/stable/bin/lein dest={{ lein_dir }}

- name: Leiningen permissions
  sudo: True
  file: path={{ lein_dir }} mode=0755
