---
- name: Set up developer group
  sudo: True
  group: name=developers state=present

- name: Set up frereth group
  sudo: True
  group: name=frereth state=present

- name: Set up non-root user
  sudo: True
  user: name=jimrthy append=yes createhome=yes groups=frereth,developers shell=/usr/bin/zsh state=present

- name: Let that new user log in
  sudo: True
  authorized_key: user=jimrthy key="{{ lookup('file', '/home/james/.ssh/todds.key.pub') }}" state=present