- name: globally install C wrapper
  command: make install chdir=/home/jimrthy/projects/jzmq

- name: Ensure future steps can find that piece
  command: ldconfig

# Note that this will probably fail from ansible: it needs manual
# intervention to enter the GPG password
- name: Install to local maven repository
  become_user: jimrthy
  command: mvn package install -Dgpg.skip=true chdir=/home/jimrthy/projects/jzmq
