---
- name: Set up a sudoer
  sudo: True
  # The groups involved seem to be OS-specific. Which may make this step more complicated.
  user: name=frereth createhome=yes shell=/usr/bin/zsh state=present system=yes append=yes groups=adm,users,sudo,admin,wheel

- name: Let frereth user log in
  sudo: True
  authorized_key: user=frereth key="{{ lookup('file', '/home/james/.ssh/todds.key.pub') }}" state=present