---
# Install java pieces that are dependent on C libraries created in previous steps

- name: autogen
  sudo: yes
  sudo_user: jimrthy
  command: ./autogen.sh chdir=/home/jimrthy/projects/jzmq

- name: configure
  sudo: yes
  sudo_user: jimrthy
  command: ./configure chdir=/home/jimrthy/projects/jzmq

- name: Build the base .class
  # Must be done before we can build the c++ pieces.
  # It seems wrong, but who am I to complain?
  sudo_user: jimrthy
  # TODO: Verify that this really does build that required file
  command: mvn clean compile chdir=/home/jimrthy/projects/jzmq

- name: make
  sudo: yes
  sudo_user: jimrthy
  command: make chdir=/home/jimrthy/projects/jzmq

- name: check
  sudo: yes
  sudo_user: jimrthy
  # Note that a failure here won't bother ansible.
  command: make check chdir=/home/jimrthy/projects/jzmq

- name: globally install C wrapper
  sudo: yes
  command: make install chdir=/home/jimrthy/projects/jzmq

- name: Install to local maven repository
  sudo_user: jimrthy
  command: mvn package install chdir=/home/jimrthy/projects/jzmq
