---
# Install java pieces that are dependent on C libraries created in previous steps

# Q: Aren't I already running this as jimrthy to begin with?
# Shouldn't I be able to ditch that part of it?

- name: experimental branch
  command: git checkout curve chdir=/home/jimrthy/projects/jzmq

- name: autogen
  command: ./autogen.sh chdir=/home/jimrthy/projects/jzmq

- name: configure
  command: ./configure chdir=/home/jimrthy/projects/jzmq

# Because this isn't getting created automatically by maven
# Then again, mvn clean turns right back around and deletes it.
#- name: place for java binary output
#  file: name=/home/jimrthy/projects/jzmq/target/classes/ group=developers owner=jimrthy state=directory

- name: Remove previous build attempts
  command: mvn clean chdir=/home/jimrthy/projects/jzmq
  ignore_errors: True

- name: Build the base .class
  # Must be done before we can actually build the c++ pieces.
  # It seems wrong, but who am I to complain?
  # TODO: Verify that this really does build that required file
  command: mvn compile chdir=/home/jimrthy/projects/jzmq

- name: make
  command: make chdir=/home/jimrthy/projects/jzmq

- name: check
  # Note that a failure here won't bother ansible.
  command: make check chdir=/home/jimrthy/projects/jzmq

# This will probably break the latest approach
# Needs the same sort of lovin' as build-sodium/0mq vs install-sodium/0mq
- name: globally install C wrapper
  sudo: yes
  command: make install chdir=/home/jimrthy/projects/jzmq

- name: Ensure future steps can find that piece
  sudo: yes
  command: ldconfig

# Note that this will probably fail from ansible: it needs manual
# intervention to enter the GPG password
- name: Install to local maven repository
  remote_user: jimrthy
  command: mvn package install chdir=/home/jimrthy/projects/jzmq
