---
# Build the required java pieces
- hosts: ubuntu-non-privileged
  roles:
  - build-jzmq
  # This next piece is purely experimental, and dubious
  - build-jni-zmq
  # Almost definitely do not want this
  - lwjgl3
