#! /bin/sh

# Really just an example of the syntax I'm using to issue a really basic
# command without ssh-agent for a default VM I just kicked off using
# the base Ubuntu distro

# Important assumptions:
# 1) That ssh key is valid and associated w/ the user on the associated hosts
ansible all --private-key=~/.ssh/todds.key -m ping -u ubuntu -i hosts

