#! /bin/bash

# Generate GPG key for later upload
# TODO: Merge that into the config file
UUID=`python -c 'import uuid; print str(uuid.uuid4())'`

# This next part's slow...don't do it often
# Especially on a VM
# It's needed to sign packages built/deployed by maven
# Since this is strictly a dev environment, you shouldn't need to be
# too horribly paranoid about it
#gpg2 --batch --gen-key roles/frereth-hacker/files/gpg-rules
#gpg2 --export-secret-key --armor thisisfake+d3091d85-e52f-4497-8f72-94ab347354ee@gmail.com > roles/frereth-hacker/files/hacker-priv_key.asc

# Set up some basic environment variables to make life easier

export ANSIBLE_HOST_KEY_CHECKING=False
export ANSIBLE_INVENTORY=`pwd`/hosts

# Note that this assumes the ansible hacking/env-setup script has already
# been source'd to properly set up environment variables.
# There are issues between '-c ssh' and '-c paramiko' that I haven't
# had any chance to dig into
# TODO: This has issues if the hosts file has a non-privileged user pointing
# at the same IP address.
# Q: What's the problem?
# If you specify the same host in multiple sections, the last one wins.
# This seems perfectly good/reasonable for something that's designed for
# deploying servers to production.
# It doesn't work so well for building dev environments.

# Most of this approach has been blocked by issues I've had trying to
# run sudo from within a container.
# Those issues seem to have gone away with btrfs, but that's due
# to my lack of knowledge/understanding.

# If I run `lxc-ls -P $btrfs-mount-point`, it looks like nothing's there.
# However, if I run `sudo lxc-ls -P $btrfs-mount-point`, it shows that
# container, stopped.

# This seems odd.

# Assuming that unprivileged containers can't sudo,
# all of these commands will really have to be accomplished via lxc-attach,
# rather than over ssh.

# There are ansible modules to cope with this sort of detail.
# It really isn't a common problem.
# TODO: Research how (and if) ansible copes with this.

ansible-playbook -i hosts baseline.yml

# Still trying to get this working again
ansible-playbook -i hosts -c ssh configure-repositories.yml


# I really wanted to make this fairly generic so I could build
# a bunch of pieces as one user, install them as a sudoer, then
# move along.
# But libzmq really depends on libsodium being installed, if
# I want to actually use it with encryption (and I do).
ansible-playbook -i hosts build-sodium.yml
ansible-playbook -i hosts_root sodium-installer.yml

ansible-playbook -i hosts build-0mq.yml
ansible-playbook -i hosts_root install-0mq.yml

# I don't think I want/need this step
# Especially since it doesn't exist
#ansible-playbook -i hosts build-jzmq.yml
# I think that should have been
#ansible-playbook -i hosts build-java-libraries.yml
#ansible-playbook -i hosts_root install-jzmq.yml
# Start Here
# Plan on replacing those with this
ansible-playbook -i hosts build-jni-zmq.yml

ansible-playbook -i hosts_root configure-web-server.yml
