---
- name: autogen 0mq configuration
  sudo: True
  sudo_user: jimrthy
  command: ./autogen.sh chdir=/home/jimrthy/projects/libzmq

- name: Configuring 0mq
  sudo: True
  sudo_user: jimrthy
  command: ./configure chdir=/home/jimrthy/projects/libzmq

- name: Make 0mq
  sudo: True
  sudo_user: jimrthy
  command: make chdir=/home/jimrthy/projects/libzmq

- name: Check 0mq
  sudo: True
  sudo_user: jimrthy
  command: make check chdir=/home/jimrthy/projects/libzmq
