---
# This is an annoying time sink when I'm debugging, but it's
# pretty vital when it comes to actual usage
- name: Update/upgrade repo cache
  sudo: True
  apt: update_cache=yes upgrade=dist

- name: Install absolute must-have packages  
  sudo: True
  apt: name={{item}} state=latest
  with_items: ${system_packages}
    
- name: Build Essentials
  sudo: True
  apt: name={{item}} state=latest
  with_items: ${build_packages}

