---
# This is an annoying time sink when I'm debugging, but it's
# pretty vital when it comes to actual usage
- name: Update/upgrade repo cache
  # sudo: True
  # Keep the cache around for (* 60 60 24) == 1 day because it gets
  # really annoying sitting around waiting on it.
  apt: update_cache=yes upgrade=dist cache_valid_time=86400

- name: Install absolute must-have packages
  #sudo: True
  apt: name={{item}} state=latest
  # N.B. These names are really ubuntu-specific.
  # TODO: I should really be doing this on arch linux.
  # Except that it doesn't play well with OpenStack.
  # TODO: Move these into ../vars/main.yml
  with_items:
    - autoconf
    - cmake
    # Q: What's the real difference between this and
    # emacs24-nox?
    # (This pulls in that)
    - emacs-nox
    - g++
    - gettext
    - git
    - gnupg2
    - iftop
    # Don't want this in a container
    #- libasound2
    - libc6
    - libgcc1
    # Also pointless in a container
    #- libgl1-mesa-dev
    # Q: What could this possibly be for in a headless
    # scenario?
    #- libgtk2.0-0
    - libstdc++6
    - libtool
    # More pieces that really are for native renderer
    #- libxcursor-dev
    #- libxi-dev
    #- libxinerama-dev
    #- libxrandr-dev
    #- libxrender1
    # Q: How useful is it to have man pages available
    # in the container?
    # A: Useful enough.
    - man-db
    # Note that this is more recent than maven2
    # (it's actually maven3)
    # I really need the OpenJDK for maven (which expects 7),
    # but that's failing
    - maven
    # Another one for the native renderer
    #- mesa-utils
    - nginx
    # TODO: Figure out a good way to keep this updated
    # That's pretty pointless, since it's another one that's
    # very specifically for the native renderer
    #- nvidia-331-uvm
    # Sadly, there's no headless version of the jdk.
    # But, in production, we only need the JRE
    # Note that this doesn't actually install in unprivileged
    # containers.
    # It depends on FUSE, which requires mknod privileges.
    # The best work-around I've found so far is at
    # https://gist.github.com/henrik-muehe/6155333
    # Actually, on xenial this seemed to "just work"
    # Which makes like drastically easier
    - openjdk-8-jdk
    - pkg-config
    - python-dev
    - python-pip
    - rlwrap
    - ssh
    - tmux
    - vim
    # Q: Do I really have a use for this?
    # A: Honestly, even if I do, it's better to install it via pip
    #- virtualenvwrapper
    #- xvfb
    #- xserver-xorg-input-kbd
    #- xserver-xorg-input-mouse
    - zsh

# Q: How do I download/extract the slimerjs .zip?
# A: Best option is probably via npm
# The binary is available at
# http://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2
# while the checksum is at
# http://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2.asc
# Q: Is there a standard ansible play for this sort of thing?

# Bigger Q: Do I care?
# slimerjs seems to be the firefox equivalent to
# phantomjs, based on chrome.
# Both are definitely worth testing, but loading either
# onto here feels wrong
