---
# This is an annoying time sink when I'm debugging, but it's
# pretty vital when it comes to actual usage
- name: Update/upgrade repo cache
  sudo: True
  # Keep the cache around for (* 60 60 24) == 1 day because it gets
  # really annoying sitting around waiting on it.
  apt: update_cache=yes upgrade=dist cache_valid_time=86400

- name: Install absolute must-have packages  
  sudo: True
  apt: name={{item}} state=latest
  # N.B. These names are really ubuntu-specific.
  # TODO: I should really be doing this on arch linux.
  # Except that it doesn't play well with OpenStack.
  with_items:
    - autoconf
    - emacs
    - g++
    - gettext
    - git
    - gnupg2
    - libtool
    - man-db
    - maven2
    # Would be using this if I were building a server.
    # Which, mostly, I am.
    # - openjdk-7-jre-headless
    - openjdk-7-jdk
    - pkg-config
    - python-dev
    - python-pip
    - ssh
    - tmux
    - vim
    - virtualenvwrapper
    # Another resource hog...do I have any use for this?
    - xrdp
    - zsh
    # Included w/ ssh
    # which means it'll be very useful for hosts where I just
    # want to install something minimalist for the sake of time
    # - wget
    # e.g.
    # - openssh-server
