---
- name: autogen libsodium configuration
  command: ./autogen.sh chdir=/home/jimrthy/projects/libsodium

- name: Configuring Libsodium
  command: ./configure chdir=/home/jimrthy/projects/libsodium

- name: Make Libsodium
  command: make chdir=/home/jimrthy/projects/libsodium

- name: Check Libsodium
  command: make check chdir=/home/jimrthy/projects/libsodium
