---
      
# I really wanted to make this fairly generic so I could build
# a bunch of pieces as one user, install them as a sudoer, then
# move along.
# But libzmq really depends on libsodium being installed, if
# I want to actually use it (and I do).
# => This particular approach cannot work.
# In all honesty, I'm back to needing a module for doing this sort
# of build.
# I'm more than a little shocked that this isn't part of core.

- name: autogen configurations
  sudo: True
  sudo_user: jimrthy
  command: ./autogen.sh chdir=/home/jimrthy/projects/{{ item }}
  with_items: projects_to_build

    
- name: Configuring libraries
  sudo: True
  sudo_user: jimrthy
  command: ./configure chdir=/home/jimrthy/projects/{{ item }}
  with_items: projects_to_build

- name: Making libraries
  sudo: True
  sudo_user: jimrthy
  command: make chdir=/home/jimrthy/projects/{{ item }}
  with_items: projects_to_build

- name: Checking
  sudo: True
  sudo_user: jimrthy
  command: make check chdir=/home/jimrthy/projects/{{ item }}
  with_items: projects_to_build


    