---
# Set up local user account customized the way I'm used to
# TODO: It's annoying that I'm using so much sudo in here. I'm
# obviously missing something basic.
# When I try to set up the task to run as the user I created in
# the beginning, things go haywire.
# This version has a lot of duplication that I hate, but it's far
# too late at night to worry about why.

- name: Configuration files
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/{{ item }} dest=/home/jimrthy/.{{ item }} backup=yes
  with_items: ${config_files_to_copy}

- name: Clone Oh! My ZSH! Repository
  sudo: True
  sudo_user: jimrthy
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/jimrthy/.oh-my-zsh

- name: Personal theme
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/jimrthy.zsh-theme dest=/home/jimrthy/.oh-my-zsh/themes/jimrthy.zsh-theme backup=yes

- name: GPG Generation Rules
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/gpg-rules dest=/home/jimrthy/gpg-rules backup=yes

# I'm a bit torn about building the GPG key now, vs. waiting until I actually need it.
# It takes long enough that it seems wise to put it off as long as possible.
# That may happen earlier if I start needing it in more places. Until then...
# It's breaking that way. So try moving it here.

- name: Default signing key (slow!)
  # A 1024-bit key run interactively took over an hour to generate
  sudo: yes
  sudo_user: jimrthy
  creates: /home/jimrthy/.gpg/secring.gpg
  command: gpg2 --batch --gen-key /home/jimrthy/gpg-rules

# TODO: Uncomment this when I'm finished debugging
# Q: Does it make any real difference?
#- name: Pre-install Leiningen
#  sudo_user: jimrthy
#  sudo: True
#  command: /usr/local/bin/lein

- name: Set up directory for local repos
  sudo: True
  sudo_user: jimrthy
  file: path=/home/jimrthy/projects state=directory

- name: Add github to known-hosts
  sudo: True
  sudo_user: jimrthy
  # TODO: At least theoretically, we shouldn't need to do this
  # That requires a newer version of ansible than I currently have
  # available.
  # FIXME: That's past tense. This seems like an extremely likely
  # candidate for just going away.
  # TODO: Test that hypothesis.
  # This one's a little tricky: I don't really want to append over
  # any existing data. I also want to make sure that this gets added.
  # Really need a way to make this idempotent.
  # TODO: There are existing external modules for handling this
  shell: ssh-keyscan github.com >> /home/jimrthy/.ssh/known_hosts_alt

- name: Copy github private key over
  sudo: True
  sudo_user: jimrthy
  copy: dest=/home/jimrthy/.ssh/github_key backup=yes src=resources/insecure.rsa mode=0600
    
- name: Use that key
  sudo: True
  sudo_user: jimrthy
  copy: dest=/home/jimrthy/.ssh/config backup=yes src=resources/ssh.config

# TODO: There are really 2 groups of repos, at least.
# Some are directly related to things I'm trying to work on right now.
# Others are pieces on which I'm building that just don't have go
# public download options, for various reasons. It makes sense to branch
# those here.
- name: Clone repositories
  sudo: True
  sudo_user: jimrthy
  git: remote=github force=no
       repo=git@github.com:jimrthy/{{ item }}.git    
       dest=/home/jimrthy/projects/{{ item }}
       key_file=/home/jimrthy/.ssh/github_key
       accept_hostkey=yes
  with_items: ${frereth_repositories}
