---
# Set up local user account customized the way I'm used to
# TODO: It's annoying that I'm using so much sudo in here. I'm
# obviously missing something basic.
# When I try to set up the task to run as the user I created in
# the beginning, things go haywire.
# This version has a lot of duplication that I hate, but it's far
# too late at night to worry about why.

- name: Root git configuration
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/gitconfig dest=/home/jimrthy/.gitconfig backup=yes

- name: Global git ignore
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/gitignore_global dest=/home/jimrthy/.gitignore_global backup=yes

- name: Configure Terminal Multiplexer
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/tmux.conf dest=/home/jimrthy/.tmux.conf backup=yes

- name: Make vi usable
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/vimrc dest=/home/jimrthy/.vimrc backup=yes

- name: Clone Oh! My ZSH! Repository
  sudo: True
  sudo_user: jimrthy
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/jimrthy/.oh-my-zsh

- name: Nice shell
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/zshrc dest=/home/jimrthy/.zshrc backup=yes

- name: Personal theme
  sudo: True
  sudo_user: jimrthy
  copy: src=resources/jimrthy.zsh-theme dest=/home/jimrthy/.oh-my-zsh/themes/jimrthy.zsh-theme backup=yes


# TODO: Uncomment this when I'm finished debugging
# Q: Does it make any real difference?
#- name: Pre-install Leiningen
#  sudo_user: jimrthy
#  sudo: True
#  command: /usr/local/bin/lein

- name: Set up directory for local repos
  sudo: True
  sudo_user: jimrthy
  file: path=/home/jimrthy/projects state=directory

- name: Add github to known-hosts
  sudo: True
  sudo_user: jimrthy
  # TODO: At least theoretically, we shouldn't need to do this
  # That requires a newer version of ansible than I currently have
  # available.
  # FIXME: That's past tense. This seems like an extremely likely
  # candidate for just going away.
  # TODO: Test that hypothesis.
  # This one's a little tricky: I don't really want to append over
  # any existing data. I also want to make sure that this gets added.
  # Really need a way to make this idempotent.
  # TODO: There are existing external modules for handling this
  shell: ssh-keyscan github.com >> /home/jimrthy/.ssh/known_hosts_alt

- name: Copy github private key over
  sudo: True
  sudo_user: jimrthy
  copy: dest=/home/jimrthy/.ssh/github_key backup=yes src=resources/insecure.rsa mode=0600
    
- name: Use that key
  sudo: True
  sudo_user: jimrthy
  copy: dest=/home/jimrthy/.ssh/config backup=yes src=resources/ssh.config

- name: Clone repositories
  sudo: True
  sudo_user: jimrthy
  git: remote=github force=no
       repo=git@github.com:jimrthy/{{ item }}.git    
       dest=/home/jimrthy/projects/{{ item }}
       key_file=/home/jimrthy/.ssh/github_key
       accept_hostkey=yes
  with_items: ${frereth_repositories}
