---
config_files_to_copy:
  - emacs.d/init.el
  - gitconfig
  - gitignore_global
  - lein/profiles.clj
  - tmux.conf
  - vimrc
  - zshrc

repositories:
    # TODO: Honestly, there are two groups of libraries here.
    # One set is underlying system pieces that I don't have any interest
    # in ever updating. I really just want a personal copy so I have a
    # baseline that doesn't get broken by everyone else.
    # Those pieces should really be attached to a 'builder' user
    # (who doesn't really have any good reason to have sudo access)
    # then installed by a sudoer.
    # The main dev user doesn't have any reason to ever think about these
    # libraries once they're installed, so they really should be hidden
    # away elsewhere anyway.
    - cljeromq
    - cljzmq
    - component-dsl
    - dareshi
    - frereth
    - frereth-client
    - frereth-common
    - frereth-renderer
    - frereth-server
    - frereth-terminal
    - frereth-web
    - lwjgl3
    # There's really no excuse for putting this in here. It will pretty
    # much never run well on a container.
    #- occultation

    # This is a very interesting possible alternative to jzmq which is most
    # likely the core of future development
    - zmq-jni

    # These are the system-level libraries that I really don't want to have
    # to ever think about.
    - jzmq
    - libsodium
    # Core library, latest development version
    # I've been neglecting it, because jzmq really wasn't keeping up
    - libzmq
    # This is looking more than a little obsolete
    - zeromq4-x
    # At the very latest, I really should start switching to this
    - zeromq4-1

# For repos that are 3rd-party enough that I desperately do not
# want to fork them
third_repositories:
  - { owner: 'creationix', repo: 'nvm' }