- name: clean
  command: ant clean chdir=/home/jimrthy/projects/lwjgl3

- name: build
  command: ant chdir=/home/jimrthy/projects/lwjgl

- name: Compress
  command: jar cf /home/jimrthy/projects/lwjgl3/lwjgl.jar *
           chdir=/home/jimrthy/projects/lwjgl3/bin/Core

- name: Index
  command: jar i lwjgl.jar chdir=/home/jimrthy/projects/lwjgl3

- name: Install Maven Repo
  command: mvn install:install-file -Dfile=lwjgl.jar -DgroupId=com.frereth -DartifactId=lwjgl -Dversion={{ lwjgl_version }} -Dpackaging=jar
           chdir=/home/jimrthy/projects/lwjgl3
