- name: clean
  command: ant clean chdir=/home/jimrthy/projects/lwjgl3

- name: build
  command: ant chdir=/home/jimrthy/projects/lwjgl3

- name: Compress
  shell: jar cf /home/jimrthy/projects/lwjgl3/lwjgl.jar *
  args:
    chdir: /home/jimrthy/projects/lwjgl3/bin/Core
    # Note that this is really just for first-time setup.
    # Future usage will replace this.
    # This little detail is just an attempt to balance
    # current dev-time debugging details against long-term
    # usage
    creates: /home/jimrthy/projects/lwjgl3/lwjgl.jar

- name: Index
  command: jar i lwjgl.jar chdir=/home/jimrthy/projects/lwjgl3

- name: Install Maven Repo
  command: mvn install:install-file -Dfile=lwjgl.jar -DgroupId=com.frereth -DartifactId=lwjgl -Dversion={{ lwjgl_version }} -Dpackaging=jar
           chdir=/home/jimrthy/projects/lwjgl3
